steps:
- name: Chekcout código
  uses: actions/checkout@v3

- name: Instalar Node.js
  uses: actions/setup-node@v3
  with:
    node-version '22'

- name: Instalar dependências
  run: npm install

- name: Rodar Testes
  run: npm test